<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>../../GFDStudio/app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../GFDLibrary/GFDLibrary.csproj" />
  </ItemGroup>
<ItemGroup><Compile Include="..\..\SLIDE\gfd_audit\*.cs" Link="Slide\%(Filename)%(Extension)" /></ItemGroup>
</Project>
